language: php
php:
  - '7.2.22'
  - hhvm

matrix:
  include:
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: hhvm
  allow_failures:
    - php: hhvm

before-install:
  - composer self-update

install:
  - composer install

script:
  - phpunit WelcomeTest.php
