language: php
php:
  - '7.2.22'

matrix:
  include:
    - php: 7.4
    - php: 7.3
    - php: 7.2

before-install:
  - composer self-update

install:
  - composer install

script:
  - vendor/bin/phpunit WelcomeTest.php
